Create comments table
MiBBy-4/onliner-analysis-app pull request #2
Opened 2022-01-12 08:16 UTC by MiBBy-4

2022-01-13 10:13 UTC, AndreyAnischik requested changes

2022-01-13 10:13 UTC, AndreyAnischik commented on app/models/article.rb
> +  validates :title, length: { minimum:3 }
add space please `{ minimum: 3 }`

2022-01-13 10:13 UTC, AndreyAnischik commented on db/migrate/20220112074341_create_comments.rb
> +      t.text :comment
rename this field to `content` or something like this

2022-01-13 10:13 UTC, AndreyAnischik commented on db/migrate/20220112080443_create_article_comments.rb
> +    create_table :article_comments do |t|
why did you decide to use many-to-many association?

2022-01-13 10:19 UTC, MiBBy-4 commented on db/migrate/20220112080443_create_article_comments.rb
> +    create_table :article_comments do |t|
So, I think that it was my mistake, cause in this case the most appropriate association is one to many, where we can link one article with many comments. Sorry, my bad. I will change it.

2022-01-13 10:50 UTC, AndreyAnischik requested changes

2022-01-13 10:50 UTC, AndreyAnischik commented on db/migrate/20220113103637_rename_comments_column_to_content.rb
> +    #Ex:- rename_column("admin_users", "pasword","hashed_pasword")
what is it? :)

2022-01-13 10:54 UTC, MiBBy-4 commented on db/migrate/20220113103637_rename_comments_column_to_content.rb
> +    #Ex:- rename_column("admin_users", "pasword","hashed_pasword")
> 

I renamed `comment` column in `comments` table to `content`

2022-01-13 11:02 UTC, AndreyAnischik requested changes

2022-01-13 11:02 UTC, AndreyAnischik commented on app/models/comment.rb
> +  has_one :article
`belongs_to`

2022-01-13 11:02 UTC, AndreyAnischik commented on db/migrate/20220112074341_create_comments.rb
> +      t.text :comment
there should be reference to articles table

2022-01-13 11:03 UTC, MiBBy-4 commented on db/migrate/20220113103637_rename_comments_column_to_content.rb
> +    #Ex:- rename_column("admin_users", "pasword","hashed_pasword")
I just realized what you mean. It  is VS Code comment. I will clear it in next commit.

2022-01-13 13:08 UTC, AndreyAnischik requested changes

2022-01-13 13:08 UTC, AndreyAnischik commented on app/models/comment.rb
> +  validates :comment
can you please specify options what it validates? also there is no more comment field for comment model.

2022-01-13 13:08 UTC, AndreyAnischik commented on app/models/comment.rb
> +  validates :username
can you please specify options what it validates?

2022-01-14 07:06 UTC, MiBBy-4 commented on app/models/comment.rb
> +  validates :comment
Yeah, I forgot about it. Check please next commit.

2022-01-14 07:08 UTC, MiBBy-4 commented on app/models/comment.rb
> +  validates :username
Done. Check please next commit. And I deleted `username` field, cause I think it is useless for analyze system

2022-01-14 07:12 UTC, MiBBy-4 commented on app/models/comment.rb
> +  validates :username
And I also added validates association for comment model with article model

2022-01-14 07:52 UTC, AndreyAnischik approved these changes

2022-01-14 07:54 UTC, merged